[naverpost]
title = "Netflix Korea ─ NAVER POST"
url = "https://m.post.naver.com/my.naver?memberNo=25425763"
entrySelector = "ul.lst_feed li._cds.check_visible"
titleSelector = "strong.tit_feed.ell"
linkSelector = "div.text_area a.link_end"
imageSelector = "div.image_area a img"
contentSelector = "p.text_feed.ell"
waitUntil = "networkidle"

[navertv]
title = "Netflix Korea ─ NAVER TV"
url = "https://tv.naver.com/netflixkr/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[vlive]
title = "Netflix Korea ─ V LIVE"
url = "https://www.vlive.tv/channel/C077D7/board/5513?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
contentSelector = "span[class^='upload_time']"
waitUntil = "networkidle"
onFail = "stale"
