[navertv]
title = "Netflix Korea ─ 네이버TV"
url = "https://tv.naver.com/netflixkr/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"

[vlive]
title = "V MOVIE"
url = "https://www.vlive.tv/channel/C077D7/board/5513?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
contentSelector = "span[class^='upload_time']"
waitUntil = "networkidle"
onFail = "stale"
